feed_name: "balance_sheet_stmts_quarterly"
type: "balance_sheet_stmts_quarterly"
full_load: true
input_datasource:
  type: "edgar_financials"
  name: "edgar_balance_sheet_stmts_source"
  stmt_type: "balance_sheet"
  period: "quarterly"
  periods: 120
  max_workers: 10
  timeout: 10
output_datasource:
  type: "postgres"
  name: "edgar_balance_sheet_stmts_sink"
  host: "HOST"
  port: "PORT"
  username: "AURUM_USERNAME"
  password: "AURUM_PASSWORD"
  db_name: "aurum"
  db_schema: "public"
  table: "balance_sheet_stmts_quarterly"
  primary_key: "MD5_HASH"
  cols_for_pk:
    - "SYMBOL"
    - "QTR"
